enum KadoNetwork {
  ETHEREUM = 'ETHEREUM',
  AVALANCHE = 'AVALANCHE',
  ARBITRUM = 'ARBITRUM',
  POLYGON = 'POLYGON',
  OPTIMISM = 'OPTIMISM',
  BITCOIN = 'BITCOIN',
  TERRA = 'TERRA',
  OSMOSIS = 'OSMOSIS',
  SOLANA = 'SOLANA',
  JUNO = 'JUNO',
  KUJIRA = 'KUJIRA',
  INJECTIVE = 'INJECTIVE',
  COSMOS_HUB = 'COSMOS HUB',
}

export default KadoNetwork
